In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pwd

'D:\\Users\\Sofia\\Documents\\script_files_all\\Python\\ml_course\\03-Pandas'

In [4]:
ls

 ’®¬ ў гбва®©бвўҐ D Ё¬ҐҐв ¬ҐвЄг Data
 ‘ҐаЁ©­л© ­®¬Ґа в®¬ : 2608-1864

 ‘®¤Ґа¦Ё¬®Ґ Ї ЇЄЁ D:\Users\Sofia\Documents\script_files_all\Python\ml_course\03-Pandas

17.10.2025  09:49    <DIR>          .
17.10.2025  09:49    <DIR>          ..
17.10.2025  09:48    <DIR>          .ipynb_checkpoints
28.10.2020  14:22    <DIR>          __pycache__
17.10.2025  09:28           568я692 00-Series.ipynb
17.10.2025  09:49           144я644 01-DataFrames.ipynb
18.01.2022  18:06           195я623 02-Conditional-Filtering.ipynb
31.05.2025  17:10           146я090 03-Useful-Methods.ipynb
31.05.2025  17:11            66я461 04-Missing-Data.ipynb
31.05.2025  17:11           224я682 05-Groupby-Operations-and-MultiIndex.ipynb
18.01.2022  18:24            66я225 06-Combining-DataFrames.ipynb
18.01.2022  18:27            34я195 07-Text-Methods.ipynb
31.05.2025  17:11           106я530 08-Time-Methods.ipynb
31.05.2025  17:18           202я222 09-Inputs-and-Outputs.ipynb
31.05.2025  17:18           106я734 10-Pivot-Tables.ipynb
17.10.2025  09:37            59я943 11-Pandas-Project-Exercise.ipynb
24.12.2023  11:31            61я218 12-Pandas-Project-Exercise-Solution.ipynb
17.10.2025  09:47                72 dataframes_practise.ipynb
04.07.2020  17:39                51 example.csv
31.05.2025  17:18             5я024 example.xlsx
12.07.2020  12:41        25я112я317 hotel_booking_data.csv
07.02.2020  12:26               177 movie_scores.csv
01.07.2020  15:56            17я727 mpg.csv
31.05.2025  17:17            25я600 my_excel_file.xls
04.07.2020  17:58             5я022 my_excel_file.xlsx
31.05.2025  17:18                46 new_file.csv
26.09.2020  12:05             5я021 new_workbook.xlsx
25.09.2020  17:16                51 newfile.csv
11.07.2020  12:14            52я132 reshaping_pivot.png
02.07.2020  17:56             5я459 RetailSales_BeerWineLiquor.csv
06.07.2020  17:10             1я320 Sales_Funnel_CRM.csv
26.09.2020  10:40             1я330 sample_table.html
31.05.2025  17:18               555 simple.html
27.01.2020  14:28            18я752 tips.csv
              30 д ©«®ў     27я233я915 Ў ©в
               4 Ї Ї®Є  281я022я439я424 Ў ©в бў®Ў®¤­®

In [5]:
df = pd.read_csv('tips.csv')

In [6]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [7]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [8]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [9]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [10]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [11]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [19]:
df['tip_precentage'] = np.round(100 * df['tip'] / df['total_bill'], 2)

In [20]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_procentage,tip_precentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97,15.97

In [22]:
df = df.drop('tip_procentage', axis=1)

In [23]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_precentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97

In [24]:
df.shape

(244, 12)